@startuml
title Use Case Đăng nhập, Đăng ký & Quên mật khẩu

left to right direction
skinparam shadowing false
actor "Người dùng" as User

rectangle "RoommieMatch" {
  (Đăng ký tài khoản) as Register
  (Đăng nhập) as Login
  (Đăng xuất) as Logout
  (Quên mật khẩu) as ForgotPassword
  (Xác thực thông tin đăng nhập) as ValidateLogin
  (Phân quyền theo vai trò) as AuthorizeRole
}

User --> Register
User --> Login
User --> Logout
User --> ForgotPassword

Login .> ValidateLogin : <<include>>
Login .> AuthorizeRole : <<include>>

@enduml


