@startuml
title Use Case Quản lý hồ sơ cá nhân

left to right direction
skinparam shadowing false
actor "Người dùng" as User

rectangle "RoommieMatch" {
  (Xem hồ sơ cá nhân) as ViewProfile
  (Cập nhật thông tin cá nhân) as UpdateProfile
  (Đổi mật khẩu) as ChangePassword
  (Xem thông báo cá nhân) as ViewNotifications
}

User --> ViewProfile
User --> UpdateProfile
User --> ChangePassword
User --> ViewNotifications

UpdateProfile .> ViewProfile : <<include>>
ChangePassword .> ViewProfile : <<include>>

@enduml


